
Basic Operations of Numpy
---

In [1]:
import numpy as np

# To create array range from 0 to 4
x = np.arange(5)
print(x)

# We could also create array in this form
y = np.arange(1,10,2)
y

[0 1 2 3 4]


array([1, 3, 5, 7, 9])

In [13]:
# To create a 2d array
b = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(b)

# Dimensions checking
print(b.ndim)

#Shape Checking
print(b.shape)

#Length Checking
print(len(b))

[[ 2  4  6]
 [ 6  8 10]]
2
(2, 3)
2


In [5]:
# using linspace
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
# Common Arrays

# Creation of singular arrays
a = np.ones((3,3))
print(a)

# Creation of Diagonal Matrix
b = np.eye(3,3)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Creation of array using diag function
z = np.diag([1,2,3,4])
z

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
# Creation of Random Array

ran = np.random.rand(4) #Uniform Distribution
print(ran)

ranx = np.random.randn(4) #Normal Distribution
print(ranx)

[0.34687521 0.43434576 0.309722   0.40707335]
[ 1.39303724 -2.27289136  0.17667956  0.96624263]


In [41]:
# Accessing, Assigning and Slicing

# 1. Acessing
a = np.array([1,2,3,4,5])
print(a[2])

# 2. Assigning
a[1] = 0
print(a)

# 3. Slicing
b = a[1::2] # From index 1 slice till last element with step size of 2
print(b)

3
[1 0 3 4 5]
[0 4]
True
False


In [47]:
# Views and Copies
# Check if two variables share same memory or not

# Here a and b are from slicing content
print(np.shares_memory(a,b)) # It is basically stating that a nd b shares same memory

c = b.copy()
print(np.shares_memory(b,c))
print(np.shares_memory(a,c))

True
False
False


In [48]:
# Fancing Arrays
# You could create array of random numbers and as many as you want

a = np.random.randint(0,10,13) # start from 0 till 10 and create 13 random integers
a

array([8, 3, 9, 4, 6, 6, 1, 9, 4, 9, 4, 7, 5])

In [51]:
# Extracting the array with the condition

mask = [a%2 == 0] # It is the same as condition
extract_from_a = a[mask] # Applying condition on arrays
print(extract_from_a)

[8 4 6 6 4 4]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


In [61]:
# Get specific positional elements of array a
a = np.arange(10)
a[[2,3,4,2]]

array([2, 3, 4, 2])

# **Numerical Operations**